### ISSUE TITLE
Stop deploying docs 

### ISSUE THREAD

**Issue by nissy-dev** [deepchem/deepchem.io#24]
When I searched by "deepchem docs", I hitted old docs (deepchem.io/docs).

<img width="1021" alt="スクリーンショット 2020-06-14 16 55 46" src="https://user-images.githubusercontent.com/17228098/84588225-8930ed80-ae60-11ea-964d-79a305b899c8.png">

I think it is not good for many users, 
so we should remove docs files in this repo and stop deploying.

**Comment by rbharath** [comment]
Good point! We should stop deploying the docs and set up a redirect so deepchem.io/docs -> deepchem.readthedocs.io.
