### ISSUE TITLE
It seems that HTTPS has expired/doesn't work

### ISSUE THREAD

**Issue by KacperKubara** [deepchem/deepchem.io#31]
Hi,
I've just noticed that when I enter the deepchem.io website, the google chrome says that the website is not secure. I don't recall that it has happened before. Maybe the HTTPS certificate has expired?

**Comment by rbharath** [comment]
Yes, you're right! This is very much on my TODO list (see https://forum.deepchem.io/t/pardon-our-dust/222). I'll try to get this fixed as soon as I can

**Comment by alat-rights** [comment]
Seems like it works now. This issue should be good to close.

![image](https://user-images.githubusercontent.com/54920181/114412536-27f4ba80-9be8-11eb-8a7f-1f06588f927d.png)

**Comment by rbharath** [comment]
<img width="1045" alt="Screen Shot 2021-04-12 at 6 50 26 PM" src="https://user-images.githubusercontent.com/1057676/114485088-362ee080-9bc0-11eb-9cc4-ea05459fc195.png">

Just tried in an incognito window and it looks like we're still saying not secure? I'm fairly sure I fixed the https certificate, and it's working on @alat-rights browser, so not sure why my browser is displaying a different answer

**Comment by alat-rights** [comment]
My browser forces HTTPS.

I think the difference is that the default being served is HTTP right now. Changing that in our DNS would make sense. 

It might also make sense for us to enable HSTS on the server for security reasons.

**Comment by alat-rights** [comment]
Resolved. HSTS is now enabled, and our site is now hosted by Github Pages. 

See #43
